/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImportedProfileView: typeof import('./src/components/ImportedProfileView.vue')['default']
    MetricChart: typeof import('./src/components/MetricChart.vue')['default']
  }
}
