// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.1
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoMetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Url   string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// cpu profile only
	ProfileSeconds uint64 `protobuf:"varint,2,opt,name=profile_seconds,json=profileSeconds,proto3" json:"profile_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GoMetricsRequest) Reset() {
	*x = GoMetricsRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoMetricsRequest) ProtoMessage() {}

func (x *GoMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoMetricsRequest.ProtoReflect.Descriptor instead.
func (*GoMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *GoMetricsRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GoMetricsRequest) GetProfileSeconds() uint64 {
	if x != nil {
		return x.ProfileSeconds
	}
	return 0
}

type GoMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          int64                  `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoMetricsResponse) Reset() {
	*x = GoMetricsResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoMetricsResponse) ProtoMessage() {}

func (x *GoMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoMetricsResponse.ProtoReflect.Descriptor instead.
func (*GoMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *GoMetricsResponse) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *GoMetricsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GoMetricsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Func          string                 `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Flat          int64                  `protobuf:"varint,3,opt,name=flat,proto3" json:"flat,omitempty"`
	Cum           int64                  `protobuf:"varint,4,opt,name=cum,proto3" json:"cum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetFunc() string {
	if x != nil {
		return x.Func
	}
	return ""
}

func (x *Item) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *Item) GetFlat() int64 {
	if x != nil {
		return x.Flat
	}
	return 0
}

func (x *Item) GetCum() int64 {
	if x != nil {
		return x.Cum
	}
	return 0
}

type DetectURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectURLRequest) Reset() {
	*x = DetectURLRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectURLRequest) ProtoMessage() {}

func (x *DetectURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectURLRequest.ProtoReflect.Descriptor instead.
func (*DetectURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *DetectURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DetectURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	HttpResult    *HTTPResult            `protobuf:"bytes,2,opt,name=httpResult,proto3,oneof" json:"httpResult,omitempty"`
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectURLResponse) Reset() {
	*x = DetectURLResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectURLResponse) ProtoMessage() {}

func (x *DetectURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectURLResponse.ProtoReflect.Descriptor instead.
func (*DetectURLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *DetectURLResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DetectURLResponse) GetHttpResult() *HTTPResult {
	if x != nil {
		return x.HttpResult
	}
	return nil
}

func (x *DetectURLResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type HTTPResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	StatusText    string                 `protobuf:"bytes,2,opt,name=statusText,proto3" json:"statusText,omitempty"`
	Body          *string                `protobuf:"bytes,3,opt,name=body,proto3,oneof" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResult) Reset() {
	*x = HTTPResult{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResult) ProtoMessage() {}

func (x *HTTPResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResult.ProtoReflect.Descriptor instead.
func (*HTTPResult) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *HTTPResult) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HTTPResult) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *HTTPResult) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x06server\"M\n" +
	"\x10GoMetricsRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12'\n" +
	"\x0fprofile_seconds\x18\x02 \x01(\x04R\x0eprofileSeconds\"a\n" +
	"\x11GoMetricsResponse\x12\x12\n" +
	"\x04date\x18\x01 \x01(\x03R\x04date\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.server.ItemR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"T\n" +
	"\x04Item\x12\x12\n" +
	"\x04func\x18\x01 \x01(\tR\x04func\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12\x12\n" +
	"\x04flat\x18\x03 \x01(\x03R\x04flat\x12\x10\n" +
	"\x03cum\x18\x04 \x01(\x03R\x03cum\"$\n" +
	"\x10DetectURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x9c\x01\n" +
	"\x11DetectURLResponse\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x127\n" +
	"\n" +
	"httpResult\x18\x02 \x01(\v2\x12.server.HTTPResultH\x00R\n" +
	"httpResult\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x01R\x05error\x88\x01\x01B\r\n" +
	"\v_httpResultB\b\n" +
	"\x06_error\"n\n" +
	"\n" +
	"HTTPResult\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x1e\n" +
	"\n" +
	"statusText\x18\x02 \x01(\tR\n" +
	"statusText\x12\x17\n" +
	"\x04body\x18\x03 \x01(\tH\x00R\x04body\x88\x01\x01B\a\n" +
	"\x05_body2\x9f\x02\n" +
	"\aMetrics\x12B\n" +
	"\vHeapMetrics\x12\x18.server.GoMetricsRequest\x1a\x19.server.GoMetricsResponse\x12A\n" +
	"\n" +
	"CPUMetrics\x12\x18.server.GoMetricsRequest\x1a\x19.server.GoMetricsResponse\x12D\n" +
	"\rAllocsMetrics\x12\x18.server.GoMetricsRequest\x1a\x19.server.GoMetricsResponse\x12G\n" +
	"\x10GoroutineMetrics\x12\x18.server.GoMetricsRequest\x1a\x19.server.GoMetricsResponse2\xa3\x02\n" +
	"\vMockMetrics\x12B\n" +
	"\vHeapMetrics\x12\x18.server.GoMetricsRequest\x1a\x19.server.GoMetricsResponse\x12A\n" +
	"\n" +
	"CPUMetrics\x12\x18.server.GoMetricsRequest\x1a\x19.server.GoMetricsResponse\x12D\n" +
	"\rAllocsMetrics\x12\x18.server.GoMetricsRequest\x1a\x19.server.GoMetricsResponse\x12G\n" +
	"\x10GoroutineMetrics\x12\x18.server.GoMetricsRequest\x1a\x19.server.GoMetricsResponse2M\n" +
	"\aGeneral\x12B\n" +
	"\tDetectURL\x12\x18.server.DetectURLRequest\x1a\x19.server.DetectURLResponse0\x01B%Z#github.com/andrewbytecoder/mgap/apib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_goTypes = []any{
	(*GoMetricsRequest)(nil),  // 0: server.GoMetricsRequest
	(*GoMetricsResponse)(nil), // 1: server.GoMetricsResponse
	(*Item)(nil),              // 2: server.Item
	(*DetectURLRequest)(nil),  // 3: server.DetectURLRequest
	(*DetectURLResponse)(nil), // 4: server.DetectURLResponse
	(*HTTPResult)(nil),        // 5: server.HTTPResult
}
var file_api_proto_depIdxs = []int32{
	2,  // 0: server.GoMetricsResponse.items:type_name -> server.Item
	5,  // 1: server.DetectURLResponse.httpResult:type_name -> server.HTTPResult
	0,  // 2: server.Metrics.HeapMetrics:input_type -> server.GoMetricsRequest
	0,  // 3: server.Metrics.CPUMetrics:input_type -> server.GoMetricsRequest
	0,  // 4: server.Metrics.AllocsMetrics:input_type -> server.GoMetricsRequest
	0,  // 5: server.Metrics.GoroutineMetrics:input_type -> server.GoMetricsRequest
	0,  // 6: server.MockMetrics.HeapMetrics:input_type -> server.GoMetricsRequest
	0,  // 7: server.MockMetrics.CPUMetrics:input_type -> server.GoMetricsRequest
	0,  // 8: server.MockMetrics.AllocsMetrics:input_type -> server.GoMetricsRequest
	0,  // 9: server.MockMetrics.GoroutineMetrics:input_type -> server.GoMetricsRequest
	3,  // 10: server.General.DetectURL:input_type -> server.DetectURLRequest
	1,  // 11: server.Metrics.HeapMetrics:output_type -> server.GoMetricsResponse
	1,  // 12: server.Metrics.CPUMetrics:output_type -> server.GoMetricsResponse
	1,  // 13: server.Metrics.AllocsMetrics:output_type -> server.GoMetricsResponse
	1,  // 14: server.Metrics.GoroutineMetrics:output_type -> server.GoMetricsResponse
	1,  // 15: server.MockMetrics.HeapMetrics:output_type -> server.GoMetricsResponse
	1,  // 16: server.MockMetrics.CPUMetrics:output_type -> server.GoMetricsResponse
	1,  // 17: server.MockMetrics.AllocsMetrics:output_type -> server.GoMetricsResponse
	1,  // 18: server.MockMetrics.GoroutineMetrics:output_type -> server.GoMetricsResponse
	4,  // 19: server.General.DetectURL:output_type -> server.DetectURLResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
